/**
 * Module: FormSubmissionModel
 * 
 * Represents the structured data returned from the Intake Form / AI Chat.
 * This is the immutable record of what the client said, plus the Magistrate's Verdict.
 */

import { z } from "zod";

// [SHARED] This schema mirrors apps/law/src/validate/schema/validate.schema.verdict.ts
// In a future refactor, this should move to packages/types
export const VerdictSchema = z.object({
  status: z.enum(['LIKELY_VIOLATION', 'POSSIBLE_VIOLATION', 'UNLIKELY_VIOLATION', 'INELIGIBLE']),
  confidence_score: z.number(),
  analysis: z.object({
    summary: z.string(),
    missing_elements: z.array(z.string()),
    strength_factors: z.array(z.string()).optional(),
    weakness_factors: z.array(z.string()).optional()
  }),
  relevant_citations: z.array(z.string())
});

export type Verdict = z.infer<typeof VerdictSchema>;

export const FormSubmissionSchema = z.object({
  id: z.string().uuid(),
  organizationId: z.string(), // [MULTI-TENANT]
  
  // Context
  formSchemaId: z.string(),
  formVersionId: z.string(),
  matterId: z.string().optional(),
  
  // The Payload
  answers: z.record(z.string(), z.any()),
  
  // Completion metadata
  isDraft: z.boolean().default(false),
  completionPercentage: z.number().min(0).max(100).default(0),
  
  // Logic/Risk Flags generated by the system
  riskScore: z.number().optional(), 
  flags: z.array(z.string()).default([]), 
  
  // [NEW] The Legal Opinion
  verdict: VerdictSchema.nullable().optional(),

  createdAt: z.date(),
  updatedAt: z.date(),
});

export type FormSubmission = z.infer<typeof FormSubmissionSchema>;