/**
 * Module: FormSubmissionModel
 * 
 * Represents the structured data returned from the Intake Form / AI Chat.
 * This is the immutable record of what the client said.
 */

import { z } from "zod";

export const FormSubmissionSchema = z.object({
  id: z.string().uuid(),
  organizationId: z.string(), // [MULTI-TENANT]
  
  // Context
  formSchemaId: z.string(),
  formVersionId: z.string(),
  matterId: z.string().optional(), // Might be a loose submission before a Matter exists
  
  // The Payload
  // We use z.record(z.any()) for the raw JSONB answers
  answers: z.record(z.string(), z.any()),
  
  // Completion metadata
  isDraft: z.boolean().default(false),
  completionPercentage: z.number().min(0).max(100).default(0),
  
  // Logic/Risk Flags generated by the system
  riskScore: z.number().optional(), // 0-100
  flags: z.array(z.string()).default([]), // e.g. ["urgent", "statute_warning"]
  
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type FormSubmission = z.infer<typeof FormSubmissionSchema>;